server:
  port: 8081

gemini:
  api-key: AIzaSyBTW8w3GNZWioi3kQbRm2KZVzbUMgKaLmU
  model: gemini-2.0-flash
  temperature: 0.7
  max-tokens: 2048

mcp:
  server:
    port: 8081
    base-url: http://localhost:8081/mcp
  tools:
    weather:
      enabled: true
    calculator:
      enabled: true
    database:
      enabled: true
    get_datetime:
        enabled: true

logging:
  level:
    com.example: DEBUG
    dev.langchain4j: INFO
    io.netty: DEBUG  # Enable Netty debug logging to see DNS resolution details
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

netty:
  dns:
    macos:
      force-resolver: true  # Force use of MacOS native DNS resolver

